In [ ]:

# CozyDay AI Prototype
# Stage 1: Research Foundation
# Model Download and Loading


import os
from pathlib import Path

os.environ["HF_HOME"] = r"D:\HuggingFace"
Path(os.environ["HF_HOME"]).mkdir(parents=True, exist_ok=True)


from transformers import AutoTokenizer, AutoModelForCausalLM

def load_model(model_id):
    """
    Download and load a Hugging Face language model.
    Model weights are cached locally, not stored in GitHub.
    """
    print(f"Loading model: {model_id}")

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(model_id)

    print("Model loaded successfully!")
    return tokenizer, model

D:\Anaconda\envs\cozyday-ai\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# CozyDay AI Prototype

## 1. Research Objective

This project evaluates 15 Hugging Face language models for a daily planning assistant integrated into the CozyDay Django application.

The AI assistant should help users:
- Summarize daily PlanItems.
- Identify high-priority tasks.
- Suggest a realistic order for completing tasks.
- Provide concise, actionable planning recommendations.

## 2. Evaluation Design

All 15 models will be evaluated using the same fixed CozyDay test inputs and expected response format.

Models will be organized into five parameter-size categories, with three models in each category.

### Evaluation Criteria

Each model will be evaluated on:

1. **Instruction Adherence (0–5):** Does the model follow the requested instructions?
2. **Output Quality (0–5):** Are its recommendations relevant, clear, and useful?
3. **Formatting Consistency (0–5):** Does the response follow the required format?
4. **Response Time (seconds):** How long does generation take?
5. **Compute Requirements:** Memory usage, hardware requirements, and loading success or failure.

Higher scores indicate better performance for the three qualitative criteria. Response time and compute requirements will be recorded separately.

## 3. Team Workflow

- Models 1–5: Lin — Research Foundation
- Models 6–10: Rishabh — Prompt Evaluation
- Models 11–15: Shivani — Local LLM Integration

The same evaluation framework and test inputs will be reused across all three stages.

In [ ]:

import pandas as pd

categories = [
    "Tiny (<0.5B)",
    "Small (0.5B-1.5B)",
    "Medium (>1.5B-3B)",
    "Large (>3B-7B)",
    "Very Large (>7B)"
]

rows = []

for round_number in range(3):
    for category in categories:
        rows.append({
            "Model No.": len(rows) + 1,
            "Category": category,
            "Model Name": "",
            "Hugging Face URL": "",
            "Parameters": "",
            "License / Access": "",
            "Hardware Requirements": "",
            "Loading Instructions": "",
            "Test Owner": ["Lin", "Rishabh", "Shivani"][round_number],
            "Status": "Not tested"
        })

model_matrix = pd.DataFrame(rows)

display(model_matrix)

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
0,1,Tiny (<0.5B),,,,,,,Lin,Not tested
1,2,Small (0.5B-1.5B),,,,,,,Lin,Not tested
2,3,Medium (>1.5B-3B),,,,,,,Lin,Not tested
3,4,Large (>3B-7B),,,,,,,Lin,Not tested
4,5,Very Large (>7B),,,,,,,Lin,Not tested
5,6,Tiny (<0.5B),,,,,,,Rishabh,Not tested
6,7,Small (0.5B-1.5B),,,,,,,Rishabh,Not tested
7,8,Medium (>1.5B-3B),,,,,,,Rishabh,Not tested
8,9,Large (>3B-7B),,,,,,,Rishabh,Not tested
9,10,Very Large (>7B),,,,,,,Rishabh,Not tested
10,11,Tiny (<0.5B),,,,,,,Shivani,Not tested
11,12,Small (0.5B-1.5B),,,,,,,Shivani,Not tested
12,13,Medium (>1.5B-3B),,,,,,,Shivani,Not tested
13,14,Large (>3B-7B),,,,,,,Shivani,Not tested
14,15,Very Large (>7B),,,,,,,Shivani,Not tested

In [ ]:

# Stage 1: Research Matrix — Tiny Models

tiny_models = [
    (0, "HuggingFaceTB/SmolLM2-135M-Instruct", "135M"),
    (5, "HuggingFaceTB/SmolLM-135M-Instruct", "135M"),
    (10, "HuggingFaceTB/SmolLM2-360M-Instruct", "360M")
]

for index, model_id, parameters in tiny_models:
    model_matrix.loc[index, "Model Name"] = model_id
    model_matrix.loc[index, "Hugging Face URL"] = (
        "https://huggingface.co/" + model_id
    )
    model_matrix.loc[index, "Parameters"] = parameters
    model_matrix.loc[index, "Hardware Requirements"] = (
        "CPU; estimate RAM needs before testing"
    )
    model_matrix.loc[index, "Loading Instructions"] = (
        "AutoTokenizer + AutoModelForCausalLM"
    )

display(model_matrix.iloc[[0, 5, 10]])

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
0,1,Tiny (<0.5B),HuggingFaceTB/SmolLM2-135M-Instruct,https://huggingface.co/HuggingFaceTB/SmolLM2-1...,135M,,CPU; estimate RAM needs before testing,AutoTokenizer + AutoModelForCausalLM,Lin,Not tested
5,6,Tiny (<0.5B),HuggingFaceTB/SmolLM-135M-Instruct,https://huggingface.co/HuggingFaceTB/SmolLM-13...,135M,,CPU; estimate RAM needs before testing,AutoTokenizer + AutoModelForCausalLM,Rishabh,Not tested
10,11,Tiny (<0.5B),HuggingFaceTB/SmolLM2-360M-Instruct,https://huggingface.co/HuggingFaceTB/SmolLM2-3...,360M,,CPU; estimate RAM needs before testing,AutoTokenizer + AutoModelForCausalLM,Shivani,Not tested

In [ ]:

# Stage 1: Research Matrix — Small Models

small_models = [
    (1, "Qwen/Qwen2.5-0.5B-Instruct", "0.5B"),
    (6, "Qwen/Qwen3-0.6B", "0.6B"),
    (11, "Qwen/Qwen2.5-1.5B-Instruct", "1.5B")
]

for index, model_id, parameters in small_models:
    model_matrix.loc[index, "Model Name"] = model_id
    model_matrix.loc[index, "Hugging Face URL"] = (
        "https://huggingface.co/" + model_id
    )
    model_matrix.loc[index, "Parameters"] = parameters
    model_matrix.loc[index, "License / Access"] = "Apache-2.0; public"
    model_matrix.loc[index, "Hardware Requirements"] = (
        "CPU possible; RAM requirement to be benchmarked"
    )
    model_matrix.loc[index, "Loading Instructions"] = (
        "AutoTokenizer + AutoModelForCausalLM"
    )

display(model_matrix.iloc[[1, 6, 11]])

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
1,2,Small (0.5B-1.5B),Qwen/Qwen2.5-0.5B-Instruct,https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct,0.5B,Apache-2.0; public,CPU possible; RAM requirement to be benchmarked,AutoTokenizer + AutoModelForCausalLM,Lin,Not tested
6,7,Small (0.5B-1.5B),Qwen/Qwen3-0.6B,https://huggingface.co/Qwen/Qwen3-0.6B,0.6B,Apache-2.0; public,CPU possible; RAM requirement to be benchmarked,AutoTokenizer + AutoModelForCausalLM,Rishabh,Not tested
11,12,Small (0.5B-1.5B),Qwen/Qwen2.5-1.5B-Instruct,https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct,1.5B,Apache-2.0; public,CPU possible; RAM requirement to be benchmarked,AutoTokenizer + AutoModelForCausalLM,Shivani,Not tested

In [ ]:

# Stage 1: Research Matrix — Medium Models

medium_models = [
    (2, "Qwen/Qwen3-1.7B", "1.7B",
     "Apache-2.0; public"),
    (7, "google/gemma-2-2b-it", "~2B",
     "Gemma license; acceptance required"),
    (12, "Qwen/Qwen2.5-3B-Instruct", "~3B",
     "Qwen Research License; public")
]

for index, model_id, parameters, license_info in medium_models:
    model_matrix.loc[index, "Model Name"] = model_id
    model_matrix.loc[index, "Hugging Face URL"] = (
        "https://huggingface.co/" + model_id
    )
    model_matrix.loc[index, "Parameters"] = parameters
    model_matrix.loc[index, "License / Access"] = license_info
    model_matrix.loc[index, "Hardware Requirements"] = (
        "Several GB RAM required; CPU may be slow"
    )
    model_matrix.loc[index, "Loading Instructions"] = (
        "AutoTokenizer + AutoModelForCausalLM; "
        "check model card and access requirements"
    )

display(model_matrix.iloc[[2, 7, 12]])

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
2,3,Medium (>1.5B-3B),Qwen/Qwen3-1.7B,https://huggingface.co/Qwen/Qwen3-1.7B,1.7B,Apache-2.0; public,Several GB RAM required; CPU may be slow,AutoTokenizer + AutoModelForCausalLM; check mo...,Lin,Not tested
7,8,Medium (>1.5B-3B),google/gemma-2-2b-it,https://huggingface.co/google/gemma-2-2b-it,~2B,Gemma license; acceptance required,Several GB RAM required; CPU may be slow,AutoTokenizer + AutoModelForCausalLM; check mo...,Rishabh,Not tested
12,13,Medium (>1.5B-3B),Qwen/Qwen2.5-3B-Instruct,https://huggingface.co/Qwen/Qwen2.5-3B-Instruct,~3B,Qwen Research License; public,Several GB RAM required; CPU may be slow,AutoTokenizer + AutoModelForCausalLM; check mo...,Shivani,Not tested

In [ ]:

# Stage 1: Research Matrix — Large Models

large_models = [
    (3, "microsoft/Phi-3.5-mini-instruct", "3.8B",
     "MIT; public"),
    (8, "Qwen/Qwen3-4B", "4B",
     "Apache-2.0; public"),
    (13, "Qwen/Qwen2.5-7B-Instruct", "7B",
     "Apache-2.0; public")
]

for index, model_id, parameters, license_info in large_models:
    model_matrix.loc[index, "Model Name"] = model_id
    model_matrix.loc[index, "Hugging Face URL"] = (
        "https://huggingface.co/" + model_id
    )
    model_matrix.loc[index, "Parameters"] = parameters
    model_matrix.loc[index, "License / Access"] = license_info
    model_matrix.loc[index, "Hardware Requirements"] = (
        "Approx. 8-14 GB FP16 weights; "
        "additional RAM needed for inference"
    )
    model_matrix.loc[index, "Loading Instructions"] = (
        "AutoTokenizer + AutoModelForCausalLM; "
        "review model-specific loading guidance"
    )

display(model_matrix.iloc[[3, 8, 13]])

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
3,4,Large (>3B-7B),microsoft/Phi-3.5-mini-instruct,https://huggingface.co/microsoft/Phi-3.5-mini-...,3.8B,MIT; public,Approx. 8-14 GB FP16 weights; additional RAM n...,AutoTokenizer + AutoModelForCausalLM; review m...,Lin,Not tested
8,9,Large (>3B-7B),Qwen/Qwen3-4B,https://huggingface.co/Qwen/Qwen3-4B,4B,Apache-2.0; public,Approx. 8-14 GB FP16 weights; additional RAM n...,AutoTokenizer + AutoModelForCausalLM; review m...,Rishabh,Not tested
13,14,Large (>3B-7B),Qwen/Qwen2.5-7B-Instruct,https://huggingface.co/Qwen/Qwen2.5-7B-Instruct,7B,Apache-2.0; public,Approx. 8-14 GB FP16 weights; additional RAM n...,AutoTokenizer + AutoModelForCausalLM; review m...,Shivani,Not tested

In [ ]:

# Stage 1: Research Matrix — Very Large Models

very_large_models = [
    (4, "Qwen/Qwen3-8B", "8.2B", 8.2),
    (9, "mistralai/Mistral-Nemo-Instruct-2407", "12B", 12.0),
    (14, "Qwen/Qwen2.5-14B-Instruct", "14.7B", 14.7)
]

for index, model_id, parameters, billions in very_large_models:
    model_matrix.loc[index, "Model Name"] = model_id
    model_matrix.loc[index, "Hugging Face URL"] = (
        "https://huggingface.co/" + model_id
    )
    model_matrix.loc[index, "Parameters"] = parameters
    model_matrix.loc[index, "License / Access"] = "Apache-2.0; public"
    model_matrix.loc[index, "Hardware Requirements"] = (
        f"FP16 weights ~{billions * 2:.1f} GB; "
        "additional RAM needed; check feasibility before loading"
    )
    model_matrix.loc[index, "Loading Instructions"] = (
        "AutoTokenizer + AutoModelForCausalLM; "
        "follow model-specific chat template"
    )

display(model_matrix.iloc[[4, 9, 14]])

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
4,5,Very Large (>7B),Qwen/Qwen3-8B,https://huggingface.co/Qwen/Qwen3-8B,8.2B,Apache-2.0; public,FP16 weights ~16.4 GB; additional RAM needed; ...,AutoTokenizer + AutoModelForCausalLM; follow m...,Lin,Not tested
9,10,Very Large (>7B),mistralai/Mistral-Nemo-Instruct-2407,https://huggingface.co/mistralai/Mistral-Nemo-...,12B,Apache-2.0; public,FP16 weights ~24.0 GB; additional RAM needed; ...,AutoTokenizer + AutoModelForCausalLM; follow m...,Rishabh,Not tested
14,15,Very Large (>7B),Qwen/Qwen2.5-14B-Instruct,https://huggingface.co/Qwen/Qwen2.5-14B-Instruct,14.7B,Apache-2.0; public,FP16 weights ~29.4 GB; additional RAM needed; ...,AutoTokenizer + AutoModelForCausalLM; follow m...,Shivani,Not tested

In [ ]:

# Complete missing license information for Tiny models

tiny_indices = [0, 5, 10]

model_matrix.loc[
    tiny_indices, "License / Access"
] = "Apache-2.0; public"

# Verify all required fields
required_columns = [
    "Model Name",
    "Hugging Face URL",
    "Parameters",
    "License / Access",
    "Hardware Requirements",
    "Loading Instructions"
]

missing = model_matrix[required_columns].isna() | (
    model_matrix[required_columns].astype(str).apply(
        lambda col: col.str.strip().eq("")
    )
)

print("Total models:", len(model_matrix))
print("Missing required fields:", int(missing.sum().sum()))
print("Unique models:", model_matrix["Model Name"].nunique())

display(model_matrix.iloc[[0, 5, 10]])

Total models: 15
Missing required fields: 0
Unique models: 15

,Model No.,Category,Model Name,Hugging Face URL,Parameters,License / Access,Hardware Requirements,Loading Instructions,Test Owner,Status
0,1,Tiny (<0.5B),HuggingFaceTB/SmolLM2-135M-Instruct,https://huggingface.co/HuggingFaceTB/SmolLM2-1...,135M,Apache-2.0; public,CPU; estimate RAM needs before testing,AutoTokenizer + AutoModelForCausalLM,Lin,Not tested
5,6,Tiny (<0.5B),HuggingFaceTB/SmolLM-135M-Instruct,https://huggingface.co/HuggingFaceTB/SmolLM-13...,135M,Apache-2.0; public,CPU; estimate RAM needs before testing,AutoTokenizer + AutoModelForCausalLM,Rishabh,Not tested
10,11,Tiny (<0.5B),HuggingFaceTB/SmolLM2-360M-Instruct,https://huggingface.co/HuggingFaceTB/SmolLM2-3...,360M,Apache-2.0; public,CPU; estimate RAM needs before testing,AutoTokenizer + AutoModelForCausalLM,Shivani,Not tested

In [ ]:

# Stage 1: Fixed CozyDay Test Inputs
# These inputs must remain unchanged across all 15 models.

test_cases = [
    {
        "test_id": "T1",
        "name": "Simple Priority Planning",
        "input": (
            "I need to finish a report due tomorrow, "
            "buy groceries, and clean my room. "
            "Which task should I prioritize and why?"
        )
    },
    {
        "test_id": "T2",
        "name": "Deadline and Time Management",
        "input": (
            "I have a meeting from 2 PM to 3 PM, "
            "an assignment due at 5 PM that needs 2 hours, "
            "and a 30-minute workout. "
            "Suggest a realistic schedule starting at 12 PM."
        )
    },
    {
        "test_id": "T3",
        "name": "Busy Day Planning",
        "input": (
            "Today I need to study for 3 hours, "
            "prepare a presentation for 2 hours, "
            "reply to emails for 30 minutes, "
            "and attend class from 1 PM to 3 PM. "
            "I am available from 9 AM to 6 PM. "
            "Help me plan my day with short breaks."
        )
    }
]

for case in test_cases:
    print(f"\n{case['test_id']}: {case['name']}")
    print(case["input"])

T1: Simple Priority Planning
I need to finish a report due tomorrow, buy groceries, and clean my room. Which task should I prioritize and why?

T2: Deadline and Time Management
I have a meeting from 2 PM to 3 PM, an assignment due at 5 PM that needs 2 hours, and a 30-minute workout. Suggest a realistic schedule starting at 12 PM.

T3: Busy Day Planning
Today I need to study for 3 hours, prepare a presentation for 2 hours, reply to emails for 30 minutes, and attend class from 1 PM to 3 PM. I am available from 9 AM to 6 PM. Help me plan my day with short breaks.


## 4. Scoring Rubric

All models will be evaluated on the same three CozyDay test cases (T1, T2, T3).

### Required Response Format

Each model should produce:

**Priority:** The most urgent task or goal.

**Schedule:** A realistic ordered plan with time slots when appropriate.

**Reason:** A short explanation of the recommended order.

The response should be concise, actionable, and avoid inventing deadlines or task constraints.

### Scoring Dimensions

Each dimension is scored from 0 to 5.

| Score | Instruction Adherence | Output Quality | Formatting Consistency |
|---|---|---|---|
| 5 | Follows all instructions | Accurate, realistic, actionable | All three sections present and clear |
| 4 | Minor instruction omission | Useful with minor issues | Minor formatting deviations |
| 3 | Follows some instructions | Partially useful or incomplete | Two sections correctly structured |
| 2 | Follows few instructions | Major omissions or planning errors | One section correctly structured |
| 1 | Barely follows instructions | Mostly irrelevant or impractical | Unstructured response |
| 0 | Does not follow instructions | No useful answer | No requested structure |

### Overall Score

Total Score = Instruction Adherence + Output Quality + Formatting Consistency

Maximum score per test case: 15 points.

Maximum score across three test cases: 45 points.

### Additional Metrics

- **Response Time:** Seconds required for generation.
- **Compute Requirements:** Device, estimated RAM usage, and loading success/failure.
- **Error Notes:** Model access restrictions, out-of-memory errors, timeouts, or other failures.

Models that cannot load or generate output will be marked as **Not evaluated** for qualitative scores. Resource failures must be documented rather than assigned an artificial score of zero.

In [ ]:

# Stage 1: Shared Baseline Prompt
# Reuse this exact instruction for all 15 models.

SYSTEM_INSTRUCTION = (
    "You are CozyDay, a helpful daily planning assistant. "
    "Use only the information provided by the user. "
    "Give realistic, concise, actionable planning advice. "
    "Do not invent deadlines or appointments. "
    "Use exactly these three headings:\n"
    "Priority:\n"
    "Schedule:\n"
    "Reason:"
)

def build_prompt(tokenizer, user_input):
    """
    Format a CozyDay request using the model's chat template
    when available, or a plain-text fallback.
    """
    messages = [
        {"role": "system", "content": SYSTEM_INSTRUCTION},
        {"role": "user", "content": user_input}
    ]

    if getattr(tokenizer, "chat_template", None):
        try:
            return tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True
            )
        except (ValueError, TypeError):
            # Some models do not support a system role.
            pass

    return (
        f"Instructions:\n{SYSTEM_INSTRUCTION}\n\n"
        f"User request:\n{user_input}\n\n"
        "Assistant response:\n"
    )

print("Baseline prompt is ready.")

Baseline prompt is ready.

In [ ]:

# Stage 1: Improved Baseline Test Harness
# Shared configuration for all 15 models

MAX_NEW_TOKENS = 256

def test_model_v2(model_id, test_cases):
    import time
    import gc
    import torch
    import pandas as pd

    results = []
    tokenizer = None
    model = None

    try:
        tokenizer, model = load_model(model_id)
        model.eval()

        for case in test_cases:
            try:
                prompt = build_prompt(tokenizer, case["input"])
                inputs = tokenizer(
                    prompt,
                    return_tensors="pt",
                    truncation=True,
                    max_length=1024
                )

                start = time.perf_counter()

                with torch.inference_mode():
                    output = model.generate(
                        **inputs,
                        max_new_tokens=MAX_NEW_TOKENS,
                        do_sample=False,
                        pad_token_id=tokenizer.eos_token_id
                    )

                elapsed = time.perf_counter() - start
                new_tokens = output[0][
                    inputs["input_ids"].shape[1]:
                ]
                response = tokenizer.decode(
                    new_tokens,
                    skip_special_tokens=True
                )

                results.append({
                    "Model": model_id,
                    "Test ID": case["test_id"],
                    "Status": "Success",
                    "Response": response,
                    "Response Time (s)": round(elapsed, 2),
                    "Generated Tokens": len(new_tokens),
                    "Reached Token Limit": (
                        len(new_tokens) >= MAX_NEW_TOKENS
                    ),
                    "Error": ""
                })

            except Exception as error:
                results.append({
                    "Model": model_id,
                    "Test ID": case["test_id"],
                    "Status": "Failed",
                    "Response": "",
                    "Response Time (s)": None,
                    "Generated Tokens": None,
                    "Reached Token Limit": None,
                    "Error": str(error)
                })

    except Exception as error:
        for case in test_cases:
            results.append({
                "Model": model_id,
                "Test ID": case["test_id"],
                "Status": "Load failed",
                "Response": "",
                "Response Time (s)": None,
                "Generated Tokens": None,
                "Reached Token Limit": None,
                "Error": str(error)
            })

    finally:
        del model
        del tokenizer
        gc.collect()

    return pd.DataFrame(results)

print("Improved baseline harness ready.")
print("Generation limit:", MAX_NEW_TOKENS)

Improved baseline harness ready.
Generation limit: 256

In [ ]:

# Load all saved CozyDay research and baseline results
# No model downloads or inference are performed here.

from pathlib import Path
import pandas as pd

results_dir = Path("results")

model_matrix = pd.read_csv(
    results_dir / "research_matrix.csv"
)

model_results = {}

for model_no in range(1, 6):
    model_results[model_no] = pd.read_csv(
        results_dir / f"model_{model_no}_results.csv"
    )

hardware_assessment = pd.read_csv(
    results_dir / "model_4_5_hardware_assessment.csv"
)

print("Research models:", len(model_matrix))
print("Baseline models loaded:", len(model_results))
print("Baseline test records:", sum(
    len(df) for df in model_results.values()
))

In [ ]:

# Stage 1 evaluation summary: Models 1–5

summary_rows = []

for model_no, df in model_results.items():
    summary_rows.append({
        "Model": model_no,
        "Test Cases": len(df),
        "Scored Cases": int(df["Total Score"].notna().sum()),
        "Total Score / 45": df["Total Score"].sum()
    })

summary_df = pd.DataFrame(summary_rows)

display(summary_df)


## Stage 1 — Results and Team Handoff

**Completed by Lin:** Research matrix of 15 Hugging Face models,
three fixed CozyDay test cases, scoring rubric, reusable test
harness, and baseline evaluation of Models 1–5.

### Inference methodology

- Models 1–3: Hugging Face Transformers.
- Models 4–5: GGUF Q4_K_M quantization with llama.cpp on CPU.
- Scores are exploratory manual evaluations, not an
  independently validated benchmark.
- Direct speed comparisons are not controlled because backend,
  precision, prompting, and timing methods differed.

### Next steps

**Rishabh:** Evaluate Models 6–10 using the shared test cases
and rubric. Document zero-shot, one-shot, few-shot, and
many-shot prompting.

**Shivani:** Continue with Models 11–15 and local LLM
integration into CozyDay.

Saved evaluations are available in `llm-test/results/`.
Do not commit downloaded model weights, secrets, or local caches.